name: CI

on:
  - push

env:
  JDK_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
      - name: Build
        run: mvn compile
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
      - name: Test
        run: mvn test
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Lint
        uses: dbelyaev/action-checkstyle@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
